# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    target-branch: "master"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "php dependency"
    ignore:
      - dependency-name: "symfony/browser-kit"
        versions: ["7.x"]
      - dependency-name: "symfony/cache"
        versions: ["7.x"]
      - dependency-name: "symfony/config"
        versions: ["7.x"]
      - dependency-name: "symfony/console"
        versions: ["7.x"]
      - dependency-name: "symfony/css-selector"
        versions: ["7.x"]
      - dependency-name: "symfony/dependency-injection"
        versions: ["7.x"]
      - dependency-name: "symfony/dom-crawler"
        versions: ["7.x"]
      - dependency-name: "symfony/dotenv"
        versions: ["7.x"]
      - dependency-name: "symfony/error-handler"
        versions: ["7.x"]
      - dependency-name: "symfony/event-dispatcher"
        versions: ["7.x"]
      - dependency-name: "symfony/filesystem"
        versions: ["7.x"]
      - dependency-name: "symfony/finder"
        versions: ["7.x"]
      - dependency-name: "symfony/framework-bundle"
        versions: ["7.x"]
      - dependency-name: "symfony/http-client"
        versions: ["7.x"]
      - dependency-name: "symfony/http-foundation"
        versions: ["7.x"]
      - dependency-name: "symfony/http-kernel"
        versions: ["7.x"]
      - dependency-name: "symfony/monolog-bridge"
        versions: ["7.x"]
      - dependency-name: "symfony/options-resolver"
        versions: ["7.x"]
      - dependency-name: "symfony/proxy-manager-bridge"
        versions: ["7.x"]
      - dependency-name: "symfony/routing"
        versions: ["7.x"]
      - dependency-name: "symfony/runtime"
        versions: ["7.x"]
      - dependency-name: "symfony/security-bundle"
        versions: ["7.x"]
      - dependency-name: "symfony/serializer"
        versions: ["7.x"]
      - dependency-name: "symfony/stopwatch"
        versions: ["7.x"]
      - dependency-name: "symfony/string"
        versions: ["7.x"]
      - dependency-name: "symfony/var-dumper"
        versions: ["7.x"]
      - dependency-name: "symfony/var-exporter"
        versions: ["7.x"]
      - dependency-name: "symfony/web-profiler-bundle"
        versions: ["7.x"]
      - dependency-name: "symfony/yaml"
        versions: ["7.x"]


  ########################################################################################################################
  #
  #   Github Actions dependencies
  #
  ########################################################################################################################
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    labels:
      - "GHA dependency"

