# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    target-branch: "master"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 15
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "php dependency"
    groups:
      symfony_dev:
        applies-to: "version-updates"
        dependency-type: "development"
        patterns:
          - "symfony/stopwatch"
          - "symfony/browser-kit"
          - "symfony/debug-bundle"
          - "symfony/css-selector"
          - "symfony/phpunit-bridge"
          - "symfony/web-profiler-bundle"
        update-types:
          - "patch"
      symfony_prod:
        applies-to: "version-updates"
        dependency-type: "production"
        patterns:
          - "symfony/*"
        update-types:
          - "patch"
    ignore:
      - dependency-name: "symfony/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor" ]

  ########################################################################################################################
  #
  #   Github Actions dependencies
  #
  ########################################################################################################################
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    labels:
      - "GHA dependency"

