httplug:
    plugins:
        retry:
            retry: 1
        cache:
            cache_pool: 'cache.app'
            stream_factory: 'httplug.stream_factory'
            config:
                respect_response_cache_directives:
                    - 'no-cache'
                    - 'max-age'
        authentication:
            github:
                type: 'bearer'
                token: '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'
        logger:
            logger: 'logger'
            formatter: null

    discovery:
        client: 'auto'

    clients:
        github:
            http_methods_client: true
            plugins:
                - 'httplug.plugin.content_length'
                - 'httplug.plugin.redirect'
                - 'httplug.plugin.retry'
                - 'httplug.plugin.authentication.github'
                - 'httplug.plugin.cache'
                - 'httplug.plugin.logger'
