env:
  global:
    - CC_TEST_REPORTER_ID=721e19591944a2b03d54b18bac024cb12cf060e5367f538d729ba32fb3fc519e

    - TEST_COVERAGE=true

    - RUN_SONAR_SCANNER=1


language: php


php:
  - 7.2
  #env: RUN_SONAR_SCANNER=1


cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "zerai"
    token:
      secure: "5cca5600ecd28c2e5a5e7e7707ab76c7da8f360b"



install:
  - composer install


before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build


script:
  - php bin/phpunit --coverage-clover clover.xml --log-junit junit.xml

  - ./cc-test-reporter after-build --coverage-input-type clover --id $CC_TEST_REPORTER_ID --exit-code $TRAVIS_TEST_RESULT

  - php vendor/bin/php-cs-fixer fix --dry-run -vvv

  - php vendor/bin/phpstan analyse


after_success:
  #- if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/php-coveralls -v; fi

  - travis_retry php vendor/bin/php-coveralls --coverage_clover clover.xml --json_path coveralls.json

  - if [[ $RUN_SONAR_SCANNER == "1" ]]; then sonar-scanner -Dsonar.projectKey=albomon -Dproject.settings=sonar-project.properties -Dsonar.projectVersion=$TRAVIS_TAG; fi