#index:
#    path: /
#    controller: App\Controller\DefaultController::index

catalog_update:
    path: /catalog/update
    controller: App\Controller\UpdateCatalogController

catalog_persist:
    path: /catalog/persist
    controller: App\Controller\UpdateAndPersistCatalogController
