name: CD/CI

on:
  push:

jobs:
  commit-stage-workflow:
    name: Commit Stage
    uses: zerai/albomon/.github/workflows/commit-stage.yaml@master
    secrets: inherit
    with:
      triggering-sha: "${{ github.sha }}"
  acceptance-stage-workflow:
    name: Acceptance Stage
    uses: zerai/albomon/.github/workflows/acceptance-stage.yaml@master
    secrets: inherit
    with:
      triggering-sha: "${{ github.sha }}"
