name: Dependabot auto-merge
on: pull_request_target

jobs:
  dependabot-auto-merge:
    name: Dependabot auto-merge
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Output Checks
        run: |
          echo ${{steps.metadata.outputs.dependency-names}}
          echo ${{steps.metadata.outputs.update-type}}
          echo ${{steps.metadata.outputs.update-type == 'version-update:semver-minor'}}
          echo ${{steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
          echo ${{steps.metadata.outputs.dependency-type}}
          echo ${{steps.metadata.outputs.dependency-type == 'direct:development'}}
      - name: Enable auto-merge only for develpment dependencies with patch-update
          if: ${{ steps.metadata.outputs.dependency-type == 'direct:development' && (steps.metadata.outputs.update-type == 'version-update:semver-patch') }}
          run: gh pr merge --auto --merge "$PR_URL"
          env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}